#eureka:
 # client:
 #   register-with-eureka: true
 #   fetch-registry: true
 #   service-url:
 #     defaultZone: http://localhost:8761/eureka/
 # instance:
 #   hostname: localhost
 spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
    
microservice: 
  agenda-service:
    endpoints: 
      endpoint: 
        uri: http://AGENDA-SERVICE/agenda/createAgenda        
  meeting-service:
    endpoints: 
      endpoint: 
        uri: http://MEETING-SERVICE/meeting/createMeeting
