server:
  port: 9008
  
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: AGENDA-SERVICE

#logging:
  #file: 
    #name: microservice.log
    #path: C:\Users\Praveen Putta\Downloads\Microservices_POC\meeting-service
    
    
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
